Header 28
Teknodev/composer-tools pull request #180
Opened 2024-04-15 08:41 UTC by kenangsmv

2024-06-03 13:48 UTC, idriska approved these changes

2024-08-06 15:43 UTC, Ayazelar commented on editor-components/header/header28/header28.module.scss
> +          color: white;
```suggestion
          color: white;
```

2024-08-06 15:44 UTC, Ayazelar commented on editor-components/header/header28/header28.tsx
> +                "https://viseo.progressionstudios.com/wp-content/uploads/2017/04/dark-poison-large-1400x700.jpg",
must be spica storage url

2024-08-06 15:44 UTC, Ayazelar commented on editor-components/header/header28/header28.tsx
> +                "https://viseo.progressionstudios.com/wp-content/uploads/2017/04/front-lines-1400x700.jpg",
must be spica storage url

2024-08-06 15:45 UTC, Ayazelar commented on editor-components/header/header28/header28.tsx
> +                "https://viseo.progressionstudios.com/wp-content/uploads/2017/04/dep-space-1400x700.jpg",
must be spica storage url

2024-08-12 14:16 UTC, Ayazelar commented on editor-components/header/header28/header28.tsx
> +                    <iframe
add classname

2024-08-12 14:16 UTC, Ayazelar commented on editor-components/header/header28/header28.tsx
> +                      <ComposerIcon name={this.getPropValue("close_icon")} />
add classname

2024-08-12 14:17 UTC, Ayazelar requested changes
.

2024-08-12 14:28 UTC, Ayazelar approved these changes

2024-08-12 14:32 UTC, merged