callToAction8
Teknodev/composer-tools pull request #239
Opened 2024-06-05 13:25 UTC by emreicandan

2024-06-05 13:40 UTC, akhnos requested changes
1. Native HTML tags should have class so the user can change the default behavior. There should be decorateCss for every element in the component
2. Button action should be handled
3. Unnecessary elements should be removed

2024-06-20 15:30 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action8/call_to_action8.tsx
> +              <h1>{this.getPropValue("title")}</h1>
should have className

2024-06-20 15:31 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action8/call_to_action8.tsx
> +                <button>
should have className

2024-06-20 15:31 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action8/call_to_action8.tsx
> +              <img src={this.getPropValue("image")} alt="" />
should have className

2024-07-01 11:53 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action8/call_to_action8.tsx
> +        "https://site.sociolib.com/dash/wp-content/uploads/sites/25/2024/04/10.png",
this image must be come from spica

2024-07-02 15:33 UTC, Ayazelar approved these changes

2024-07-02 15:33 UTC, merged