header26
Teknodev/composer-tools pull request #248
Opened 2024-06-27 09:22 UTC by yusufktlk

2024-06-27 11:15 UTC, Ayazelar commented on editor-components/header/header26/header26.module.scss
> +      // }
remove unused codes

2024-06-27 11:15 UTC, Ayazelar commented on editor-components/header/header26/header26.module.scss
> +            // flex-direction: row !important;
remove

2024-06-27 11:16 UTC, Ayazelar commented on editor-components/header/header26/header26.tsx
> +        slide.classList.add(styles.shrink);
use decorate css method

2024-06-27 11:17 UTC, Ayazelar requested changes
.

2024-07-25 15:02 UTC, dogusmiuw requested changes
please handle changes

2024-07-25 15:02 UTC, dogusmiuw commented on editor-components/header/header26/header26.tsx
> +            {this.castToObject<[]>("sliders").map((item: any, index: number) => (
after creating the relevant type, cast it to that.
e.g. `this.castToObject<SliderItem[]>("sliders").map((item: SliderItem, ...`

2024-07-25 15:02 UTC, dogusmiuw commented on editor-components/header/header26/header26.tsx
> +                    </ComposerLink>
if item.title is empty, do not render this. do this operation for all props.
[please check](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-25 15:02 UTC, dogusmiuw commented on editor-components/header/header26/header26.tsx
> +                      alt="Slider Image"
```suggestion
                      alt={this.castToString(item.title)}
```

2024-08-16 07:20 UTC, Ayazelar approved these changes

2024-08-16 07:41 UTC, dogusmiuw approved these changes

2024-08-16 07:42 UTC, merged