Feature5
Teknodev/composer-tools pull request #249
Opened 2024-06-28 10:14 UTC by yapmakutu

2024-07-02 08:11 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.tsx
> +        },
the URL must be spica storage URL

2024-07-02 08:12 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.tsx
> +                "https://demo.tagdiv.com/newspaper_lifestyle_pro/wp-content/uploads/2020/06/29-1068x1417.jpg",
the URL must be spica storage URL

2024-07-02 08:12 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.tsx
> +              value: "https://demo.tagdiv.com/newspaper_lifestyle_pro/wp-content/uploads/2020/06/28-696x696.jpg",
the URL must be spica storage URL

2024-07-02 08:12 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.tsx
> +                "https://demo.tagdiv.com/newspaper_lifestyle_pro/wp-content/uploads/2020/06/27-696x870.jpg",
the URL must be spica storage URL

2024-07-02 08:12 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.tsx
> +                "https://demo.tagdiv.com/newspaper_lifestyle_pro/wp-content/uploads/2020/06/26-696x464.jpg",
the URL must be spica storage URL

2024-07-02 08:12 UTC, Ayazelar requested changes
.

2024-07-25 13:26 UTC, dogusmiuw requested changes
please handle the changes

2024-07-25 13:26 UTC, dogusmiuw commented on editor-components/feature/feature5/feature5.tsx
> +      };
create a type for this. it will be more cleaner

2024-07-25 13:26 UTC, dogusmiuw commented on editor-components/feature/feature5/feature5.tsx
> +              value: "https://www.google.com/",
```suggestion
              value: "",
```

2024-07-27 10:18 UTC, dogusmiuw approved these changes
code approved. waiting for ui review

2024-08-28 15:14 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.module.scss
There should not be a static bit height value. Heights should be taken according to the text value.

2024-09-02 15:11 UTC, Ayazelar commented on editor-components/feature/feature5/feature5.tsx
> +                        }}
remove inline style

2024-09-02 15:13 UTC, Ayazelar requested changes
.

2024-09-04 12:21 UTC, Ayazelar approved these changes

2024-09-05 07:50 UTC, merged