Calltoaction6
Teknodev/composer-tools pull request #252
Opened 2024-07-01 14:56 UTC by yapmakutu

2024-07-02 08:13 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action6/call_to_action6.module.scss
> +                //box-shadow: 0 2px 4px rgba(var(--composer-font-color-primary-rgb), 0.1);
```suggestion
```

2024-07-02 08:13 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action6/call_to_action6.tsx
> +        "https://c4.wallpaperflare.com/wallpaper/869/24/987/hand-writing-book-man-wallpaper-preview.jpg",
the URL must be spica storage URL

2024-07-02 08:14 UTC, Ayazelar commented on editor-components/call_to_action/call_to_action6/call_to_action6.tsx
> +    const isButtonEmpty = icon || this.castToString(button.button_text);
this shouldn't be like     const isButtonEmpty = icon || !this.castToString(button.button_text);

2024-07-02 08:14 UTC, Ayazelar requested changes
.

2024-07-25 13:29 UTC, dogusmiuw requested changes
please handle changes

2024-07-25 13:29 UTC, dogusmiuw commented on editor-components/call_to_action/call_to_action6/call_to_action6.tsx
> +      link: string;
create a type for this.
[please read](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md)

2024-08-21 15:39 UTC, Ayazelar approved these changes

2024-08-21 15:57 UTC, dogusmiuw approved these changes

2024-08-21 15:57 UTC, merged