Download6
Teknodev/composer-tools pull request #253
Opened 2024-07-01 14:57 UTC by yapmakutu

2024-07-02 08:16 UTC, Ayazelar commented on editor-components/download/download6/download6.tsx
> +    const isButtonEmpty =
check variables if there is button text the button is not empty

2024-07-02 08:16 UTC, Ayazelar requested changes
.

2024-07-25 13:31 UTC, dogusmiuw requested changes

2024-07-25 13:31 UTC, dogusmiuw commented on editor-components/download/download6/download6.module.scss
> +                    font-size: 3.4vw;
vw doesn't look appropriate for font-size property.

2024-08-16 07:17 UTC, Ayazelar approved these changes

2024-08-16 07:42 UTC, dogusmiuw approved these changes

2024-08-16 08:02 UTC, merged