feature6
Teknodev/composer-tools pull request #254
Opened 2024-07-03 13:32 UTC by EmomaxD

2024-07-03 14:11 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.module.scss
> +                    overflow: hidden; /* Added to clip the scaled image */
```suggestion
                    overflow: hidden;
```

2024-07-03 14:11 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.module.scss
> +                        transition: transform .3s ease; /* Added ease transition */
```suggestion
                        transition: transform .3s ease; 
```

2024-07-03 14:11 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.module.scss
> +                        top: 55%; /* Adjusted to cover the bottom 45% */
```suggestion
                        top: 55%; 
```

2024-07-03 14:12 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.module.scss
> +                        height: 45%; /* Adjusted to cover the bottom 45% */
```suggestion
                        height: 45%;
```

2024-07-03 14:12 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.module.scss
> +                gap: 20px !important; /* Decreased gap for smaller screens */
```suggestion
                gap: 20px !important;
```

2024-07-03 14:12 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.module.scss
> +                    gap: 5px; /* Decreased gap for buttons on smaller screens */
```suggestion
                    gap: 5px;
```

2024-07-03 14:12 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.tsx
> +                "https://demo.tagdiv.com/newspaper_interior_designer_pro/wp-content/uploads/2023/11/10-3-696x928.jpg",
should use spica storage url

2024-07-03 14:12 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.tsx
> +                "https://demo.tagdiv.com/newspaper_interior_designer_pro/wp-content/uploads/2023/11/9-3-696x614.jpg",
should use spica storage url

2024-07-03 14:12 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.tsx
> +                "https://demo.tagdiv.com/newspaper_interior_designer_pro/wp-content/uploads/2023/11/50-3-696x510.jpg"
should use spica storage url

2024-07-03 14:13 UTC, Ayazelar requested changes
.

2024-07-25 09:43 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 09:43 UTC, dogusmiuw commented on editor-components/feature/feature6/feature6.tsx
> +            <div className={this.decorateCSS("header-title")}>{this.getPropValue("header")}</div>
If no title entered, remove its relevant elements. Do this for all.

2024-07-25 09:43 UTC, dogusmiuw commented on editor-components/feature/feature6/feature6.tsx
> +type Button = {
Unused code. Remove it.

2024-07-25 09:43 UTC, dogusmiuw commented on editor-components/feature/feature6/feature6.tsx
> +      }
Can you explain this section? Why did you choose this way? And why do you need it?

2024-07-29 15:10 UTC, dogusmiuw commented on editor-components/feature/feature6/feature6.tsx
> +import { BaseFeature, TypeUsableComponentProps } from "../../EditorComponent";
remove TypeUsableComponentProps from this import

2024-08-16 07:14 UTC, Ayazelar commented on editor-components/feature/feature6/feature6.tsx
> +                              className={`
use className instead inline style

2024-08-16 07:15 UTC, Ayazelar requested changes
.

2024-08-16 11:28 UTC, Ayazelar approved these changes

2024-08-16 11:38 UTC, dogusmiuw approved these changes

2024-08-16 12:20 UTC, merged