download-7
Teknodev/composer-tools pull request #256
Opened 2024-07-04 09:11 UTC by emirhandumann

2024-07-05 07:26 UTC, Ayazelar commented on editor-components/download/download7/download7.tsx
> +    }, 100);
what if the user doesn't want an animation?

2024-07-05 07:27 UTC, Ayazelar commented
please undo registrables changes and commit again

2024-07-25 08:36 UTC, dogusmiuw requested changes

2024-07-25 08:36 UTC, dogusmiuw commented on editor-components/download/download7/download7.tsx
> +              <h6 className={this.decorateCSS("contentTitle")}>
For all props, remove their relevant elements when there is no input for them.

2024-08-16 07:10 UTC, Ayazelar approved these changes

2024-08-16 07:43 UTC, dogusmiuw approved these changes

2024-08-16 08:01 UTC, merged