stats5
Teknodev/composer-tools pull request #259
Opened 2024-07-08 07:09 UTC by emirhandumann

2024-07-25 08:41 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 08:41 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +              (data: any, index: number) => (
change data: CardData

2024-07-25 08:41 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +                  <h4 className={this.decorateCSS("card-data-title")}>
Remove divs when there is no input. Do this for all.

2024-07-29 12:16 UTC, dogusmiuw requested changes

2024-07-29 12:16 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +                    </p>
don't render p element if data.description is empty.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 12:16 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +                    </h4>
don't render h4 if {this.getComponentState(`number-${index}`)} is empty
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 12:16 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +    const hasCard = this.castToObject<CardData[]>("cardContent").length > 0;
```suggestion
    const cards = this.castToObject<CardData[]>("cardContent");
```

2024-07-29 12:16 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +          {hasCard && (
```suggestion
          {cards.length > 0 && (
```

2024-07-29 12:16 UTC, dogusmiuw commented on editor-components/stats/stats5/stats5.tsx
> +              {this.castToObject<CardData[]>("cardContent").map(
```suggestion
              {cards.map(
```

2024-08-21 16:28 UTC, Ayazelar approved these changes

2024-08-21 16:33 UTC, dogusmiuw approved these changes

2024-08-21 16:36 UTC, merged