Appereance tweak
Teknodev/composer-tools pull request #260
Opened 2024-07-08 07:57 UTC by Avassaa

Fixed feature12

2024-07-09 07:34 UTC, Ayazelar commented on editor-components/feature/feature12/feature12.module.scss
> +                background-image: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.75)), url('https://avo.themescamp.com/wp-content/uploads/2020/09/1-2.jpg');
if this value does not come from the prop the user cannot change the background image

2024-07-09 07:35 UTC, Ayazelar commented on editor-components/feature/feature12/feature12.tsx
> +        key: "message", //TODO:BURASI
```suggestion
        key: "message",
```

2024-07-09 07:35 UTC, Ayazelar commented on editor-components/feature/feature12/feature12.tsx
> +                        <div>
should have className

2024-07-09 07:36 UTC, Ayazelar commented on editor-components/feature/feature12/feature12.tsx
> +              {firstItem[1].value}
please do not use values like that. check new components

2024-07-09 07:37 UTC, Ayazelar commented on editor-components/feature/feature12/feature12.tsx
We don't recommend using inline CSS as it increases code complexity. It's better to move them to an SCSS file.

2024-07-09 07:37 UTC, Ayazelar requested changes
.

2024-07-25 10:04 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 10:04 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
>    }
Consider this format:
```js
 this.addProp({
      type: "number",
      key: "itemCountInRow",
      displayer: "Item Count in a Row",
      value: 4,
      max: 4,
    });
```

2024-07-29 12:09 UTC, dogusmiuw requested changes
please handle the changes

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +    const backgroundImage = firstItem[2].value;
don't access values like this. please create a type for firstItem object.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-approach-props)

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +        </div>
don't use inline css. move them into the scss file.
don't render relevant divs if the prop is empty.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +      <div className={this.decorateCSS("container")} style={{ paddingBottom: "0px" }}>
don't use inline css. move them into the scss file.

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +        </div>
don't use inline css. move them into the scss file.
don't render relevant divs if the prop is empty.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +        </div>
don't use inline css. move them into the scss file.
don't render relevant divs if the prop is empty.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +            {firstItem.length > 0 && (
firstItem = prop "message" is an object. it doesn't have length. it is not an array.
it is an object so we should create a type for it.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-approach-props)

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +                <h3 className={this.decorateCSS("title")}>{firstCardTitle}</h3>
don't render h3 if firstCardTitle is empty.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 12:09 UTC, dogusmiuw commented on editor-components/feature/feature12/feature12.tsx
> +                </button>
don't render this button if buttonText is empty.
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-08-21 16:16 UTC, Ayazelar approved these changes

2024-08-21 16:24 UTC, dogusmiuw approved these changes

2024-08-21 16:24 UTC, merged