notification-modal1
Teknodev/composer-tools pull request #262
Opened 2024-07-08 08:08 UTC by Goktugberke

2024-07-25 13:06 UTC, Goktugberke commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +        maxElementCount: 1,
They requested that there should be an overlay on the image in the banner. When the image is deleted, the div should be removed. The overlay to be added on top of the image should be shown as a checkbox in the props, allowing the user to choose whether to use the component with or without the overlay. That's why I implemented it as an array. I believe it doesn't work any other way.

2024-07-26 09:43 UTC, Goktugberke commented
Sadece editorcomponents.tsx dosyasındaki Location kodunu kaldırdığımda 416-417 satırlarında hata veriyor. Ve onları kaldırdığım zaman blinkpagede hata düzelmiyor. Ancak 81. satırdaki  " LOCATION = "Location", "  kodunu yazarsak componentim sıkıntısız çalışıyor. Change requestte kaldır dediğiniz için orayı kaldırdım ama.

2024-07-28 15:58 UTC, dogusmiuw requested changes

2024-07-28 15:58 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +              </h3>
do not render h3 if secondTitle prop is empty.
[check here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-28 15:58 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +              </p>
do not render p if description prop is empty
[check here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-28 15:58 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +              ))}
if item.buttonText is empty, do not render it.

```suggestion
              {this.castToObject<Button[]>("buttonprops").map((item: Button, index: number) => {
                if(this.castToString(item.buttonText))
                  return (
                  <ComposerModalClose key={index}>
                    <a href={item.link} className={this.decorateCSS("button")}>
                      {item.buttonText}
                    </a>
                  </ComposerModalClose>
                )
              })}
```

2024-07-28 15:58 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +        "https://c4.wallpaperflare.com/wallpaper/149/547/831/violet-gradient-abstract-wallpaper-preview.jpg",
use spica storage url

2024-07-29 15:16 UTC, dogusmiuw approved these changes

2024-07-30 15:31 UTC, dogusmiuw requested changes
please handle css changes

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +          background-color: darkblue;
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +      background-color: rgba(230, 230, 232, 0.447);
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +        background-color: rgb(28, 143, 243);
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +          color: blue;
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +        color: gray;
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +        color: red;
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +          color: white;
no static colors in css

2024-07-30 15:31 UTC, dogusmiuw commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +      background: white;
no static colors in css

2024-08-28 14:35 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +      max-height: 650px;
remove max-height cause the user may want write long text

2024-08-28 14:38 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +          }
overlay2 and overlay3 should be not there. you can make it with one overlay

2024-08-28 14:39 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +          }
make it one

2024-08-28 14:42 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +      }
seems unnecessery remove

2024-08-28 14:42 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +    console.log("backgroundImage  " + backgroundImage)
remove log

2024-08-28 14:44 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +                    <ComposerIcon propsIcon={{ className: this.decorateCSS("exit-icon"), style: { width: "25px", height: "25px" } }} name={this.getPropValue("exitIcon")} />
Don't use inline CSS, as it makes code readability harder.

2024-08-28 14:46 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +            </div>
refactor it

2024-08-28 14:47 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +    const isTitleExist = this.castToString(this.getPropValue("secondTitle"));
rename this variable

2024-08-28 14:48 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.tsx
> +                  <div className={this.decorateCSS("deneme")}>
change "deneme"

2024-08-28 14:48 UTC, Ayazelar requested changes
change

2024-09-04 10:48 UTC, Ayazelar approved these changes

2024-09-05 13:45 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +    width: var(--composer-content-width);
use screen width instead of --composer-content-width. cause when the --composer-content-width reduces the content width also reduces.

2024-09-05 13:45 UTC, Ayazelar requested changes
.

2024-09-05 13:46 UTC, Ayazelar commented on editor-components/modal/notification-modal1/notificationmodal1.module.scss
> +    width: var(--composer-content-width);
```suggestion
    width: 100vw;
```

2024-09-05 13:46 UTC, Ayazelar approved these changes

2024-09-05 15:06 UTC, dogusmiuw approved these changes

2024-09-05 15:06 UTC, merged