notificationalmodal2
Teknodev/composer-tools pull request #264
Opened 2024-07-08 08:46 UTC by sudeakinci

2024-07-25 08:09 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 08:09 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.module.scss
> +
Add media queries.
For screens that their width is under the modal's width, make their width 100%.

2024-07-25 08:09 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +      key: "e-mail",
Don't use kebab-case in "key"s.

2024-07-25 08:09 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +                propsIcon={{ className: this.decorateCSS("text")}}
Change 
`propsIcon = ... this.decorateCSS("text")`
to
`propsIcon = ... this.decorateCSS("Icon")`

2024-07-25 08:09 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +                   {buttonval[0].value && (
Find another way to access button value. 
We should not use it like buttonval[0].value etc

2024-07-25 08:09 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +                          {buttonval[0].value}
Find another way to access button value.
We should not use it like buttonval[0].value etc

2024-07-25 08:09 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +      key: "button",
This does not need to be an object. User is only going to enter button text. It can be just string.

2024-07-29 14:56 UTC, dogusmiuw requested changes
please handle the changes

2024-07-29 14:56 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +              {description}
this should be like:
```suggestion
              {this.getPropValue("displayerMessage")}
```

2024-07-29 14:56 UTC, dogusmiuw commented on editor-components/modal/notificationmodal2/notificationmodal2.tsx
> +                        {buttonval}
this should be like:
```suggestion
                        {this.getPropValue("button")}
```

2024-07-29 15:34 UTC, dogusmiuw approved these changes

2024-08-21 13:25 UTC, Ayazelar commented on editor-components/modal/notificationmodal2/notificationmodal2.module.scss
> +        font-family: sans-serif;
remove font-family

2024-08-21 13:25 UTC, Ayazelar commented on editor-components/modal/notificationmodal2/notificationmodal2.module.scss
> +        font-family: sans-serif;
remove font-family

2024-08-21 13:30 UTC, Ayazelar requested changes
change

2024-08-21 14:49 UTC, merged