Creation of image gallery 2
Teknodev/composer-tools pull request #270
Opened 2024-07-09 06:02 UTC by Avassaa

2024-07-09 07:24 UTC, Ayazelar commented on editor-components/Image_gallery/image_gallery_2/image-gallery2.tsx
The image values must be come from spica storage

2024-07-09 07:28 UTC, Ayazelar commented on editor-components/Image_gallery/image_gallery_2/image-gallery2.tsx
> +                                        <ComposerIcon propsIcon={{ className: this.decorateCSS("magnifier-icon") }} name="FaSearch" />
the name of icon must be come from prop

2024-07-09 07:29 UTC, Ayazelar commented on editor-components/Image_gallery/image_gallery_2/image-gallery2.tsx
> +                                &#10095;
you should use composer icon component instead of &#10094; &#10095;

2024-07-09 07:32 UTC, Ayazelar requested changes
The changes to the image gallery and the feature12 should be separated into two separate processes.

2024-07-11 09:42 UTC, Avassaa commented on editor-components/Image_gallery/image_gallery_2/image-gallery2.tsx
Do i have to initialize a spica storage myself or is there any source for that

2024-07-25 10:05 UTC, dogusmiuw commented
Please exclude feature12 files and send this again

2024-07-25 15:37 UTC, closed without merging