Feature7
Teknodev/composer-tools pull request #271
Opened 2024-07-09 09:57 UTC by samednayki

Feature7 ara yüzü tasarlandı , tıklama animasyonu eklendi ve başka linke gitme halledildi

2024-07-25 14:09 UTC, dogusmiuw approved these changes
LGTM!

2024-08-27 15:12 UTC, Ayazelar commented on editor-components/feature/feature7/feature7.tsx
> +
rename this variables

2024-08-28 10:14 UTC, Ayazelar commented on editor-components/feature/feature7/feature7.tsx
>      const hasTextContent =
check line 179. you are using "hasTextContent.length". It has a bit of a strange spelling

2024-08-28 10:14 UTC, Ayazelar requested changes
change

2024-08-28 15:38 UTC, dogusmiuw approved these changes

2024-08-28 15:40 UTC, Ayazelar approved these changes

2024-08-28 15:45 UTC, merged