Content19
Teknodev/composer-tools pull request #272
Opened 2024-07-09 12:18 UTC by mustafaozger

2024-07-25 11:45 UTC, dogusmiuw commented
exclude feature 9 from this pull request. and send it again

2024-07-26 12:46 UTC, mustafaozger commented
I've revert the feature9 commit

2024-07-29 11:56 UTC, dogusmiuw requested changes
please handle changes

2024-07-29 11:56 UTC, dogusmiuw commented on editor-components/content/content19/content19.tsx
> +              {this.getProp("title-text").value && (
```suggestion
              {this.getProp("title-text", { as_string: true }) && (
```

2024-07-29 11:56 UTC, dogusmiuw commented on editor-components/content/content19/content19.tsx
> +                  <p className={"author-description-text"}>{this.getPropValue("author-description")}</p>
don't render this if author-description is empty

2024-07-29 11:56 UTC, dogusmiuw commented on editor-components/content/content19/content19.tsx
> +                  <h1 className={"author--text"}>{this.getPropValue("author-name")}</h1>
don't render this if author-name is empty

2024-07-29 11:56 UTC, dogusmiuw commented on editor-components/content/content19/content19.tsx
> +                  return null;
```suggestion
```

2024-07-29 11:56 UTC, dogusmiuw commented on editor-components/content/content19/content19.tsx
> +                {(this.getProp("buttons").value as any[]).map((buttonObj, index) => {
don't map arrays like this.
[check here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-map-things)

2024-07-29 11:56 UTC, dogusmiuw commented on editor-components/content/content19/content19.tsx
> +                  const buttonData = buttonObj.value;
don't access values like this -> asdf.value

2024-08-01 10:02 UTC, mustafaozger commented
I changed my code based on your feedback

2024-08-26 12:19 UTC, Ayazelar commented on editor-components/content/content19/content19.tsx
> +                  <span className="as-play" onClick={() => {
should use decorateCSS

2024-08-26 12:20 UTC, Ayazelar commented on editor-components/content/content19/content19.tsx
> +              (this.castToString(titleText) || this.castToString(description) || this.castToString(authorDescription) || this.castToString(authorName) || this.castToObject<ButtonProps[]>("buttons").l
use a variable name like "displaycontent" maybe

2024-08-26 12:21 UTC, Ayazelar requested changes
.

2024-08-27 15:02 UTC, Ayazelar approved these changes

2024-08-27 15:03 UTC, dogusmiuw approved these changes

2024-08-27 15:03 UTC, merged