formmodal1
Teknodev/composer-tools pull request #275
Opened 2024-07-11 07:47 UTC by sudeakinci

2024-07-25 08:21 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 08:21 UTC, dogusmiuw commented on editor-components/modal/formmodal1/formmodal1.module.scss
> +
Add media queries.
Same comment for notificationModal2. Apply the same.

2024-07-25 08:21 UTC, dogusmiuw commented on editor-components/modal/formmodal1/formmodal1.tsx
> +          type: "array",
Create a type for this prop.

2024-07-25 08:21 UTC, dogusmiuw commented on editor-components/modal/formmodal1/formmodal1.tsx
> +              key: "input-item",
Use camelCase for all keys.

2024-07-25 08:21 UTC, dogusmiuw commented on editor-components/modal/formmodal1/formmodal1.tsx
> +              <div className={this.decorateCSS("left-page")}>
If there is no image uploaded, delete img's div. Make the other divs strech for available space.

2024-07-29 11:47 UTC, dogusmiuw commented
please exclude registerables.tsx file from the pr and send again

2024-07-29 14:03 UTC, dogusmiuw approved these changes

2024-08-29 13:47 UTC, Ayazelar requested changes
.

2024-09-05 12:50 UTC, Ayazelar commented on editor-components/modal/formmodal1/formmodal1.tsx
> +                  propsIcon={{ className: this.decorateCSS("exit-icon"), style: { width: "25px", height: "25px" } }}
remove style and give that values in CSS file

2024-09-05 12:51 UTC, Ayazelar requested changes
.

2024-09-05 13:38 UTC, Ayazelar approved these changes
.

2024-10-18 07:45 UTC, merged