feedbackmodal1
Teknodev/composer-tools pull request #276
Opened 2024-07-11 09:26 UTC by Goktugberke

2024-07-25 11:34 UTC, dogusmiuw requested changes
handle the changes

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          alt=""  className={this.decorateCSS("icon")}/>
image alt field should not be empty

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +    const placeholder = inputItems?.[0]?.value?.[1]?.value?.[0]?.value?.[0]?.value || "Add a Comment...";
do not access values like this

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +        value:"https://www.google.com/imgres?q=comment%20icon&imgurl=https%3A%2F%2Ficons.veryicon.com%2Fpng%2Fo%2Fhardware%2Fjackdizhu_pc%2Fcomment-25.png&imgrefurl=https%3A%2F%2Fwww.veryicon.com%2Fi
this should not be a link. it should be name of the icon. e.g. : FaArrowDown

[please read](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md)

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +];
icon cannot be an emoji. also remove this array. add this prop hard coded into the constructor. remove the map.

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +      value: emojis.map(emoji => ({
this should be hard coded. remove map

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +  id: number;
revisit type according to feedbacks

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +import * as Yup from "yup";
never import all from a package. only import things that you need.

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAdVBMVEX///8AAACOjo4xMTF4eHjm5ubv7++urq4SEhJSUlKXl5cPDw/MzMyUlJRDQ0PX19ekpKT5+flra2vz8/OBgYFkZGTf39+6urpJSUlbW
this should be a prop. also add this image using a google storage link

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +            const label = item?.value?.[0]?.value;
do not access values like this

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          {this.castToObject<any[]>("emojiProps")?.map((item: any, index: number) => {
do not use any. write a reliable type for this. also cast it while mapping too.
`.map((item: TYPE_THAT_YOUVE_WRITTEN, index....`

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +                <span className={this.decorateCSS("feedbackModalEmojiIcon")}>{icon}</span>
do not render relevant elements if there is no icon entered. do this operation for all props

2024-07-25 11:34 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +  }
add media queries for mobile

2024-07-29 15:06 UTC, dogusmiuw requested changes

2024-07-29 15:06 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          />
if feedback_icon prop is empty, don't render composerIcon

2024-07-29 15:06 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          </h1>
if title prop is empty, don't render this h1 element.
[read here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 15:06 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +        </div>
if title prop is empty, don't render this div element.
[read here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 15:06 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +        </div>
if title prop is empty, don't render this div element.
[read here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-29 15:06 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +        </div>
render this div only if emojiProps.length > 0

2024-07-29 15:06 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +                  Submit Now
transform this "Submit Now" text into a prop. user should be able to change it

2024-08-09 14:44 UTC, dogusmiuw requested changes
please handle the changes

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +  font-family: 'Arial', sans-serif;
do not use font family

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +    border-bottom: 1px solid #eee;
do not use static color

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +      background-color: #d2d1d13a;
do not use static colors

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +    flex-direction: row;
default value is already : row. remove this line

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +      flex-direction: row;
default value is already : row. remove this line

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +        //border: 0.5px solid rgba(var(--composer-font-color-primary-rgb), 0.3);
remove comment line

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +    border: 1px solid #ddd;
do not use static colors

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +  @media (max-width: 768px) {
```suggestion
  @media only screen and (max-width: 768px) { 
```

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.module.scss
> +  @media (max-width: 480px) {
```suggestion
  @media only screen and (max-width: 480px) { 
```

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +};
invalid type.
[please read](https://github.com/Teknodev/composer-tools/tree/main/editor-components#how-to-approach-props)

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          {isHeaderTitleExist &&
do not just remove h2. remove all the div

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +          {isDescriptionExist &&
do not just remove p, remove all the div

2024-08-09 14:44 UTC, dogusmiuw commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +            {emojiProps.map((item: Emoji, index: number) => (
```suggestion
            {emojiProps.map((item: Emoji, index: number) => {
            
            if(item.value)
                return (
```

2024-08-28 14:58 UTC, Ayazelar requested changes
.

2024-08-29 12:27 UTC, Ayazelar commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +    message: Yup.string().min(5, "Min 5 character!").required("Required"),
the messages must come from the prop. user may want to change message

2024-08-29 12:28 UTC, Ayazelar commented on editor-components/feedback/feedbackmodal1/feedbackmodal1.tsx
> +                this.insertForm("Contact Us", data);
data should be like this= {
input_0: "",
input_1: ""
}

2024-08-29 12:28 UTC, Ayazelar requested changes
change

2024-09-02 15:16 UTC, Ayazelar requested changes
inserted form data should be like this= {
input_0: "Message of the input. lOrem ips",
input_1: ""
}

2024-12-09 07:16 UTC, closed without merging