header32
Teknodev/composer-tools pull request #278
Opened 2024-07-12 09:27 UTC by emirhandumann

2024-07-26 07:32 UTC, dogusmiuw requested changes
please handle the changes

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +  urlTitle: string;
```suggestion
  imageTitle: JSX.Element;
  imageDescription: JSX.Element;
  urlTitle: JSX.Element;
```

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +type AppendDotsFunction = NonNullable<Settings["appendDots"]>;
remove

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +              value: "https://themes.pixelwars.org/archy/demo-01/wp-content/uploads/sites/2/2023/05/daniel-stone-A4TtfFo_qRw-unsplash.jpg",
should be spica storage url

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +                            {item.imageTitle}
it its empty, do not render relevant elements

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +                              {item.imageDescription}
it its empty, do not render relevant elements

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +                                  {item.urlTitle}
it its empty, do not render relevant elements

2024-07-26 07:32 UTC, dogusmiuw commented on editor-components/header/header32/header32.tsx
> +                                name={this.getPropValue("leftButton")[0].value}
do not access values like this: ...[0].value...

2024-09-04 07:30 UTC, alperensen commented
Updated header32

2024-09-11 15:35 UTC, Ayazelar commented on editor-components/header/header32/header32.module.scss
> +
there is the same animation named descriptionBottom. delete this one

2024-09-11 15:36 UTC, Ayazelar commented on editor-components/header/header32/header32.module.scss
> +                    text-overflow: ellipsis;
check mixin and include in scss

2024-09-11 15:39 UTC, Ayazelar commented on editor-components/header/header32/header32.tsx
> +          </div>
it looks like the button and span seem unnecessary. also, use decorateCss in classNames

2024-09-11 15:40 UTC, Ayazelar requested changes
change

2024-09-13 15:03 UTC, merged