New Content16.
Teknodev/composer-tools pull request #281
Opened 2024-07-15 18:45 UTC by mehmetcanozen

Made with reference to "Latest News" section of this page:                                                                                                                                https://themes.pixelwars.org/archy/demo-01/

2024-07-17 07:18 UTC, Ayazelar reviewed
Image "alt" property shouldn't be an empty string, it can be title or subTitle. All HTML code should be SEO optimized.

2024-07-25 09:54 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 09:54 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +              key: "image_subtitle",
Use camelCase for all keys.

2024-07-25 09:54 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +type Card = {
Wrong format.

[Please read this.](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md)

2024-07-29 14:49 UTC, dogusmiuw requested changes
try to make that animation without using keyframe. try to implement it with transition

2024-07-31 04:00 UTC, mehmetcanozen commented
I could not switch the animations from keyframes to transition so I removed them altogether. Other than that made the requested changes.

2024-07-31 09:53 UTC, dogusmiuw commented on editor-components/content/content16/content16.module.scss
> +
i guess .container needs background-color: var(--composer-html-background)

2024-07-31 10:38 UTC, dogusmiuw requested changes

2024-07-31 10:38 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +};
why all optional? remove "?" from these.

also the types are wrong.

```javascript
title: JSX.Element;
subtitle: JSX.Element;
description: JSX.Element;
imageTitle: JSX.Element;
imageSubtitle: JSX.Element;
imageTitle: JSX.Element;
```

others can stay as the same

2024-07-31 10:38 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +      (item: CardType) => item.image || item.imageTitle || item.imageSubtitle || item.url
imageTitle and imageSubtitle should be casted to string

2024-07-31 10:38 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +                      key={`sld-16-${index}`}
you can just say `key={index}`

2024-07-31 10:38 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +                                alt={item.imageTitle || item.imageSubtitle}
they should be casted to string

2024-07-31 10:38 UTC, dogusmiuw commented on editor-components/content/content16/content16.tsx
> +                        )}
they should be casted to string while doing empty check, because they return JSX element.

2024-07-31 10:39 UTC, dogusmiuw commented
exclude calltoaction7 files from this pr

2024-08-29 13:51 UTC, Ayazelar commented on editor-components/content/content16/content16.tsx
> +import Slider from "react-slick";
use composerslider

2024-08-29 13:52 UTC, Ayazelar requested changes
.

2024-09-06 15:19 UTC, Ayazelar commented on editor-components/content/content16/content16.module.scss
> +}
remove

2024-09-06 15:25 UTC, Ayazelar commented on editor-components/content/content16/content16.tsx
> +                            this.castToString(item.imageTitle) ? {} : { padding: "20px 10px" }
remove inline style

2024-09-06 15:25 UTC, Ayazelar requested changes
.

2024-09-10 07:56 UTC, merged