The structure whose icons are used as images in all flutters has been converted to Composer Icon format.
Teknodev/composer-tools pull request #283
Opened 2024-07-16 08:17 UTC by yapmakutu

2024-07-17 07:15 UTC, Ayazelar reviewed
Image "alt" props shouldn't be an empty string, it can be something like the title or some other text. All HTML code should be SEO optimized.

2024-07-25 13:38 UTC, dogusmiuw requested changes
apply the change requests for all the files

2024-07-25 13:38 UTC, dogusmiuw commented on editor-components/footer/footer1/footer1.tsx
> +              <h1 className={this.decorateCSS("subscriptionTitle")}>
if prop is empty, then remove relevany elements. do this for all props

2024-07-25 13:38 UTC, dogusmiuw commented on editor-components/footer/footer10/footer10.tsx
> +      value: "https://www.google.com/",
use empty string for link props

2024-07-25 13:38 UTC, dogusmiuw commented on editor-components/footer/footer10/footer10.tsx
> +      key: "ref-page",
use camelCase for keys

2024-07-25 13:38 UTC, dogusmiuw commented on editor-components/footer/footer10/footer10.tsx
> +                <a href={this.getPropValue("ref-page")}>
if prop is empty, do not render relevant elements

2024-10-18 07:42 UTC, closed without merging