Header20
Teknodev/composer-tools pull request #284
Opened 2024-07-16 08:17 UTC by yapmakutu

2024-07-17 07:12 UTC, Ayazelar reviewed
So many "if case" used, it should be reduced

2024-07-25 13:40 UTC, dogusmiuw requested changes

2024-07-25 13:40 UTC, dogusmiuw commented on editor-components/header/header20/header20.tsx
> +                "http://clapat.ro/themes/hervin-wordpress/wp-content/uploads/2019/05/09hero.jpg",
use spica storage url

2024-09-12 07:56 UTC, Ayazelar commented on editor-components/header/header20/header20.module.scss
> +            // max-width: fit-content;
remove unused style

2024-09-12 07:58 UTC, Ayazelar commented on editor-components/header/header20/header20.module.scss
> +              transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1) 0.3s;
use varaible for transition

2024-09-12 08:05 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +  };
```suggestion
```

2024-09-12 08:05 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +  debounce = <T extends (...args: any[]) => void>(func: T, delay: number): ((...args: Parameters<T>) => void) => {
delete debounce function cause unused

2024-09-12 08:05 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +      console.log("yukarı");
remove log

2024-09-12 08:05 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +    console.log("up")
remove log

2024-09-12 08:05 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +    console.log("next slider", nextSlide)
remove log

2024-09-12 08:07 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +    this.setComponentState("commentSlider", nextSlide);
create a function for this cause you are using line 921

2024-09-12 08:18 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +                        </a>
Use ComposerLink and remove onMouseEnter and onMouseLeave.

2024-09-12 08:19 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +  };
check this function seem unnessasary

2024-09-12 08:19 UTC, Ayazelar requested changes
.

2024-09-13 15:05 UTC, Ayazelar approved these changes

2024-09-13 15:05 UTC, Ayazelar commented on editor-components/header/header20/header20.tsx
> +                          <ComposerLink>
give path

2024-09-13 15:05 UTC, Ayazelar requested changes
.

2024-09-17 08:24 UTC, Ayazelar approved these changes

2024-09-17 08:25 UTC, merged