image_gallery_5 initial commit
Teknodev/composer-tools pull request #287
Opened 2024-07-19 07:30 UTC by sudeakinci

2024-07-22 09:57 UTC, akhnos reviewed
Overlay background is not responding when the user scroll down.

2024-07-25 07:53 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_5/image-gallery5.tsx
> +}
Do not use interface, use type. `type ImageType = {`

[Read this file](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md)

2024-07-25 07:54 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_5/image-gallery5.tsx
> +          value: "https://arty.flatheme.net/assets/images/p-clean-2-1.jpg"
Change all this image URLs with spica storage URL.

You can get these URLs with uploading the images.

2024-07-25 07:58 UTC, dogusmiuw requested changes
Please handle requests.

2024-07-25 07:58 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_5/image-gallery5.tsx
> +    const galleries = this.getPropValue("gallery");
Change with the type that you have written.
```javascript
const galleries = this.castToObject<ImageType[]>("gallery");
```

[Please read.](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md)

2024-07-25 07:58 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_5/image-gallery5.tsx
> +                    src={image.value}
Please revisit these values after updating the ImageType.

2024-07-30 15:01 UTC, dogusmiuw approved these changes

2024-09-17 08:14 UTC, Ayazelar commented on editor-components/Image_gallery/image_gallery_5/image-gallery5.module.scss
> +          width: 482px;
It will not fit on some phone screens. Must be responsive

2024-09-17 08:16 UTC, Ayazelar commented on editor-components/Image_gallery/image_gallery_5/image-gallery5.tsx
> +  }
Are you sure this is working? Lifecycle hooks should not be working.

2024-09-17 08:17 UTC, Ayazelar requested changes
.

2024-09-19 12:34 UTC, Ayazelar approved these changes

2024-09-25 10:57 UTC, Ayazelar approved these changes

2024-09-25 11:39 UTC, merged