Created image gallery7
Teknodev/composer-tools pull request #291
Opened 2024-07-22 07:39 UTC by Avassaa

2024-07-22 09:44 UTC, akhnos reviewed
using global css elements are forbidden, the component scss file can only contain classnames it reproduces

2024-07-22 11:48 UTC, Avassaa commented
Tekrardan kontrol edebilirsiniz, kodu düzelttim

2024-07-25 08:31 UTC, dogusmiuw commented
Only send image gallery 7 files.

2024-07-25 09:24 UTC, dogusmiuw requested changes
Please handle the changes.

2024-07-25 09:24 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +  const cardBackgroundColor = this.getPropValue("cardBackgroundColor") as string || "#f1f1e8";
I don't think this is going to work. Prop key is not correct.

2024-07-25 09:32 UTC, dogusmiuw commented
This is a new component. Import this component into registerables.tsx file.

2024-07-29 13:09 UTC, dogusmiuw requested changes
please handle the changes

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 1",
use singular and non-contain number names.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "Image 1",
use singular and non-contain number names.
```suggestion
                        displayer: "Image",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "title",
```suggestion
                                displayer: "Title",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "subtitle",
```suggestion
                                displayer: "Subtitle",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 2",
use singular and non-contain number names.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "Image 2",
use singular and non-contain number names.
```suggestion
                        displayer: "Image",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "title",
```suggestion
                                displayer: "Title",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "subtitle",
```suggestion
                                displayer: "Subtitle",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 3",
use singular and non-contain number names.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "Image 3",
```suggestion
                                displayer: "Image",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "title",
```suggestion
                                displayer: "Title",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "subtitle",
```suggestion
                                displayer: "Subtitle",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 4",
use singular and non-contain number names.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "Image 4",
```suggestion
                                displayer: "Image",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "title",
```suggestion
                                displayer: "Title",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "subtitle",
```suggestion
                                displayer: "Subtitle",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 5",
use singular and non-contain number names.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "Image 5",
```suggestion
                                displayer: "Image",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "title",
```suggestion
                                displayer: "Title",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "subtitle",
```suggestion
                                displayer: "Subtitle",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 6",
use singular and non-contain number names.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "Image 6",
```suggestion
                                displayer: "Image",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "title",
```suggestion
                                displayer: "Title",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                                displayer: "subtitle",
```suggestion
                                displayer: "Subtitle",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                        displayer: "Card 7",
use singular and non-contain number names. do this for all.
```suggestion
                        displayer: "Card",
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +          <div key={columnIndex} className={`${this.decorateCSS("column")} ${this.decorateCSS(`column-${columnIndex}`)}`}>
find a better way for this -> ```${this.decorateCSS(`column-${columnIndex}`)}```
```suggestion
          <div key={columnIndex} className={`${this.decorateCSS("column")} ${this.decorateCSS(`column-${columnIndex}`)}`}>
```

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +      } as React.CSSProperties}
doesn't seem right.

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                const image = card.value.find(item => item.type === "image") as ImageType;
dont cast values like this. use this.castToObject

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                const title = card.value.find(item => item.key === "title") as unknown as { type: "string"; key: string; displayer: string; value: string };
dont cast values like this. create a type for it and use this.castToObject.

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                const subtitle = card.value.find(item => item.key === "subtitle") as unknown as  { type: "string"; key: string; displayer: string; value: string };
dont cast values like this. create a type for it and use this.castToObject.

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                const backgroundColor = card.value.find(item => item.key === "backgroundColor")?.value as string || cardBackgroundColor;
dont cast values like this. create a type for it and use this.castToObject.

2024-07-29 13:09 UTC, dogusmiuw commented on editor-components/Image_gallery/image_gallery_7/image-gallery7.tsx
> +                      <div className={this.decorateCSS("subtitle")}>{subtitle.value}</div>
don't render relevant elements if prop is empty
[see here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-11-28 17:45 UTC, closed without merging