stats2
Teknodev/composer-tools pull request #293
Opened 2024-07-25 10:36 UTC by EmomaxD

2024-07-25 12:12 UTC, dogusmiuw requested changes
please handle changes

2024-07-25 12:12 UTC, dogusmiuw commented on editor-components/stats/stats2/stats2.tsx
> +            <div className={this.decorateCSS("header")}>{this.getPropValue("header")}</div>
remove relevant if `this.getPropValue("header")` value is empty

[check this out](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-25 12:12 UTC, dogusmiuw commented on editor-components/stats/stats2/stats2.tsx
> +              {this.getPropValue("subHeader")}
remove relevant if `this.getPropValue("subHeader")` value is empty

[check this out](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-25 12:12 UTC, dogusmiuw commented on editor-components/stats/stats2/stats2.tsx
> +              <button className={this.decorateCSS("contact-button")}>{this.getPropValue("contactButton")}</button>
remove button if `this.getPropValue("contactButton")` value is empty

[check this out](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-25 12:12 UTC, dogusmiuw commented on editor-components/stats/stats2/stats2.tsx
> +            {cards.map((card, index) => (
```suggestion
            {cards.map((card: Card, index: number) => (
```

2024-07-25 12:12 UTC, dogusmiuw commented on editor-components/stats/stats2/stats2.tsx
> +}
you do not need to create another component for this. there is an example for number animation in stats6.

2024-07-25 12:27 UTC, dogusmiuw commented
also this component doesnt look like the original one. please check carefully

2024-07-27 10:54 UTC, dogusmiuw requested changes
do not use functional component

2024-07-27 10:54 UTC, dogusmiuw commented on editor-components/stats/stats2/stats2.tsx
> +};
remove this we do not use functional components

2024-09-12 08:32 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.module.scss
> +          border-top: 1px solid rgba(var(--composer-font-color-primary-rgb), 0.2);
```suggestion
      border: 1px solid rgba(var(--composer-font-color-primary-rgb), 0.2);
      border-bottom: none;
```

2024-09-12 08:33 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.tsx
> +                style={{ top: hasHeader ? "245px" : "0" }}
don't use inline style

2024-09-12 08:34 UTC, Ayazelar requested changes
.

2024-09-26 14:37 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.tsx
> +              <div className={this.decorateCSS("header")}>{header}</div>
use this.getPropValue

2024-09-26 14:37 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.tsx
> +                 {subHeader}
use getPropValue

2024-09-26 14:38 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.tsx
> +                   {contactButton}
use getPropValue

2024-09-26 14:38 UTC, Ayazelar requested changes
.

2024-10-16 15:25 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.tsx
> +                propsIcon={{ className: styles["card-icon-after"] }}
use decorateCss

2024-10-16 15:25 UTC, Ayazelar requested changes
.

2024-12-26 15:16 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.module.scss
> +            padding: 1rem 2rem;
use gap varaible

2024-12-26 15:17 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.module.scss
> +        top: 5rem;
when the font size changed the top position also will changed. is that expected?

2024-12-26 15:17 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.module.scss
> +              margin-left: .5rem;
use gap value

2024-12-26 15:17 UTC, Ayazelar commented on editor-components/stats/stats2/stats2.module.scss
> +            padding: 2rem 2.5rem;
use gap value

2024-12-26 15:20 UTC, Ayazelar requested changes
.

2024-12-30 17:15 UTC, KardelennArslan commented on editor-components/stats/stats2/stats2.module.scss
> +          padding: 1rem 3rem 1.5rem 3rem;
use gap value

2024-12-31 07:40 UTC, merged