stats-7
Teknodev/composer-tools pull request #294
Opened 2024-07-25 12:08 UTC by CenkerAydin

2024-07-25 12:59 UTC, dogusmiuw requested changes
please handle changes

2024-07-25 12:59 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +interface Item {
```suggestion
type Item {
 title: JSX.Element;
 progress: number;
 progressText: JSX.Element;
}
```

[please check](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md)

2024-07-25 12:59 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +              key: "progess-title",
use camelCase for all keys. also keys must be same as you declared in type that you have written. ex:
```js
type Item {
 title: JSX.Element;
 progress: number;
 progressText: JSX.Element;
}
```

2024-07-25 12:59 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +          {subtitle && <div className={this.decorateCSS("title-child")}>
for empty string check please read the documentation.

[read here](https://github.com/Teknodev/composer-tools/blob/main/editor-components/README.md#how-to-check-if-a-string-prop-is-empty)

2024-07-25 12:59 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +              const title = item.value[0].value;
dont access props like this

2024-07-25 12:59 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +            {this.getPropValue("items").map((item: any, index: number) => {
please cast to object. use the type you wrote.
```suggestion
            {this.castToObject<Item[]>("items").map((item: Item, index: number) => {
```

2024-07-27 11:03 UTC, dogusmiuw requested changes

2024-07-27 11:03 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +
```suggestion
if(this.castToString(title) || this.castToString(text))
```

2024-07-27 11:03 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +            {this.castToObject<Item[]>("items").map((item: any, index: number) => {
```suggestion
            {this.castToObject<Item[]>("items").map((item: Item, index: number) => {
```

2024-07-29 11:38 UTC, dogusmiuw requested changes
please handle the changes

2024-07-29 11:38 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +                    </div>
don't render if {text} is empty

2024-07-29 11:38 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
>                    </div>
render if title or text is not empty

2024-07-29 12:40 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
> +        font-family: "Roboto", sans-serif;
do not use font family

2024-07-29 12:41 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
do not use font family and use px or % on margins

2024-07-29 12:42 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
use height values in the height prop. do not use rem

2024-07-29 12:52 UTC, dogusmiuw requested changes

2024-07-29 12:52 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +            {this.castToObject<Item[]>("items").map((item: Item, index: number) => {
declare this between redner and return statemens.
```javascript
const items = this.castToObject<Item[]>("items");
```
```suggestion
            {items.map((item: Item, index: number) => {
```

2024-07-29 12:52 UTC, dogusmiuw commented on editor-components/stats/stats7/stats7.tsx
> +              }
you may try to find a better way for this check

2024-07-29 14:43 UTC, dogusmiuw approved these changes

2024-09-20 14:15 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
> +
remove

2024-09-20 14:16 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +                backgroundColor: `${enableSubtitleBackground ? "" : 'transparent' }`
remove inline style

2024-09-20 14:17 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +              }}>{isSubtitleExist}</h1>
use getPropValue

2024-09-20 14:17 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +              <h1 className={this.decorateCSS("title")}>{isTitleExist}</h1>
use getPropValue

2024-09-20 14:17 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +                {isDescriptionExist}
use getPropValue

2024-09-20 14:17 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +                        {title}
use getPropValue

2024-09-20 14:17 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +                              {text}
use getPropValue

2024-09-20 14:17 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.tsx
> +                      <div className={this.decorateCSS("progress-title")}>
what if title not exists

2024-09-20 14:17 UTC, Ayazelar requested changes
.

2024-09-26 14:40 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
> +      .progress-active {
that's duplicate check line 88. remove one

2024-09-26 14:41 UTC, Ayazelar requested changes
.

2024-10-03 15:14 UTC, Ayazelar requested changes
remove duplicated styles on css side

2024-10-16 15:20 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
> +      // justify-content: end;
remove

2024-10-16 15:21 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
> +        // gap: 20px;
```suggestion
```

2024-10-16 15:21 UTC, Ayazelar commented on editor-components/stats/stats7/stats7.module.scss
> +      // justify-content: end;
```suggestion
```

2024-10-16 15:22 UTC, Ayazelar approved these changes

2024-10-16 15:40 UTC, merged