content-13
Teknodev/composer-tools pull request #295
Opened 2024-07-25 12:17 UTC by CenkerAydin

2024-07-25 13:06 UTC, dogusmiuw requested changes
please handle changes

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.module.scss
> +    background-image: url("https://craftohtml.themezaa.com/images/vertical-center-line-bg.svg");
this should be a prop in JSX oart. also we use google storage url for image links

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.module.scss
> +                    margin-left: 10px; // İsteğe bağlı: buton ile diğer içerik arasındaki boşluk
delete redundant comment

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.module.scss
> +@media only screen and (max-width: 1024px) and (min-width:768px) {
using only max-width for media queries is enough

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +      key: "about-title",
use camelCase for all keys

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +      key: "maintitle",
use camelCase

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +      displayer: "maintitle",
```suggestion
      displayer: "Main Title",
```

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +      displayer: "Text of Button",
```suggestion
      displayer: "Button Text",
```

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +      value: "https://craftohtml.themezaa.com/images/demo-hotel-and-resort-home-01.jpg"
use google storage urls for images

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +      value: "https://craftohtml.themezaa.com/images/demo-hotel-and-resort-home-02.jpg"
use google storage urls for images

2024-07-25 13:06 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +              <img src={this.getPropValue("image2")} alt="" className={this.decorateCSS("image2")} />
image alt should be non-empty.

also this images do not seem right and overflows in desktop and mobile previews.

2024-07-27 11:05 UTC, dogusmiuw requested changes
please handle changes

2024-07-27 11:05 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +            <span className={this.decorateCSS("about-title")}>{this.getPropValue("aboutTitle")}</span>
if prop is empty, do not render relevant elements. do this operation for all props

2024-07-29 11:33 UTC, dogusmiuw requested changes
please handle changes

2024-07-29 11:33 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +            { isAboutTitleExist && <span className={this.decorateCSS("about-title")}>{isAboutTitleExist}</span>}
do this for all
```suggestion
            { isAboutTitleExist && <span className={this.decorateCSS("about-title")}>{this.getPropValue("aboutTitle")}</span>}
```

2024-07-29 11:33 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +              </button>
```suggestion
 {isButtonTextExist &&
              <button className={this.decorateCSS("about-button")}>
               <div className={this.decorateCSS("buttonText")}>{this.getPropValue("buttonText")}</div>
              </button>
```

2024-07-29 11:33 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
>            </div>
```suggestion
{(this.getPropValue("image1") || this.getPropValue("image2")) &&
          <div className={this.decorateCSS("right-page")}>
            <div className={this.decorateCSS("image-container")}>
              {isTextExist && <h1 className={this.decorateCSS("text")}>{isTextExist}</h1> }
              {isYearExist && <h2 className={this.decorateCSS("year")}>{isYearExist}</h2>}
              <img src={this.getPropValue("image1")} alt="Image 1" className={this.decorateCSS("image1")} />
              <img src={this.getPropValue("image2")} alt="Image 2" className={this.decorateCSS("image2")} />
            </div>
          </div>
          }
```

2024-07-29 11:33 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +              <div className={this.decorateCSS("phone-icon")}>
```suggestion
{(this.getPropValue("phoneIcon") || isPhoneExist) &&
              <div className={this.decorateCSS("phone-icon")}>
```

2024-07-29 11:33 UTC, dogusmiuw commented on editor-components/content/content13/content13.tsx
> +                {isPhoneExist && <h1 className={this.decorateCSS("phone")}>{isPhoneExist}</h1>}
```suggestion
                {isPhoneExist && <h1 className={this.decorateCSS("phone")}>{this.getPropValue("phone")}</h1>}
```

2024-07-29 12:18 UTC, dogusmiuw approved these changes
waiting for ui review

2024-09-13 15:13 UTC, Ayazelar approved these changes

2024-09-13 15:14 UTC, merged