stats8 pr moved here
Teknodev/composer-tools pull request #298
Opened 2024-07-27 10:44 UTC by dogusmiuw

2024-07-27 10:46 UTC, dogusmiuw reviewed
code approved. waiting for ui review

2024-09-13 15:15 UTC, Ayazelar commented on editor-components/stats/stats8/stats8.module.scss
you can use variables in scss. please check

2024-09-13 15:19 UTC, Ayazelar commented on editor-components/stats/stats8/stats8.tsx
> +                    {title}
use this.getPropValue cause you are using cast to string above. if you are using string the inline editor does not appear in strings

2024-09-13 15:19 UTC, Ayazelar requested changes
.

2024-09-19 12:37 UTC, Ayazelar approved these changes

2024-11-20 11:32 UTC, closed without merging