add: create base navbar component
Teknodev/composer-tools pull request #685
Opened 2024-12-26 17:54 UTC by kenangsmv

2024-12-26 23:52 UTC, kenangsmv commented
spliting position value is throwing an error due to being undefined

2024-12-27 12:22 UTC, Ayazelar commented on composer-base-components/base/base.module.scss
> +        padding: 20px;
can't we use gap value?

2024-12-27 12:22 UTC, Ayazelar requested changes
.

2024-12-27 12:39 UTC, Ayazelar approved these changes

2024-12-27 12:39 UTC, merged